apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pvwebviewers.pvviewer.com
spec:
  group: pvviewer.com
  names:
    kind: PvWebViewer
    listKind: PvWebViewerList
    plural: pvwebviewers
    singular: pvwebviewer
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
